[Service]
#
# Privilege De-escalation
#
User=mysql
Group=mysql





#
# Resource limits
#
# Adjust as needed for your scale.
RestrictRealtime=true
TasksMax=512
MemoryMax=1G
MemoryHigh=800M





#
# Filesystem protections
#
# Adjust as needed for your setup.
UMask=077
RuntimeDirectoryMode=755
WorkingDirectory=
ProtectSystem=strict
ProtectHome=tmpfs
ReadWritePaths=/var/lib/mysql /var/log/mysql /run/mysqld
BindReadWritePaths=
ReadOnlyPaths=
BindReadOnlyPaths=
NoExecPaths=/tmp /var/tmp /dev/shm






#
# Capability limitations
#
# Adjust as needed.
SystemCallArchitectures=native
SystemCallFilter=~@clock @cpu-emulation @debug @module @mount @obsolete @swap @privileged @resources
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX
CapabilityBoundingSet=
AmbientCapabilities=
#
# Allow IPC for local comm. w/ databases
RemoveIPC=false





#
# Filesystem Protections
#
ProtectProc=invisible
NoNewPrivileges=true
LockPersonality=true
RestrictNamespaces=true
RestrictSUIDSGID=true
ProtectControlGroups=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectKernelLogs=true
ProtectClock=true
ProtectHostname=true
PrivateTmp=true
PrivateDevices=true
DevicePolicy=closed
#
# May break some applications
PrivateUsers=true
