[Service]
# Restrict control access (crucial for a service with high privilege)
ProtectControlGroups=true
ProtectKernelTunables=true
LockPersonality=true

# Restrict memory/capabilities
MemoryDenyWriteExecute=true
NoNewPrivileges=true
