# Require length of 10
minlen = 10
#
# Require 1 all 4 character types
dcredit = -1
ucredit = -1
lcredit = -1
ocredit = -1
#
# Similarity / repetition limits
difok = 4
maxrepeat = 4
maxclassrepeat = 10
retry = 3
#
# Enforce the restrictions for the root user's password
enforce_for_root
