# General settings for all users
*	hard	nproc	512
*	hard	nofile	1024
*	hard	stack	8192
*	hard	core	0
*	hard	priority	0
*	hard	cpu	180
*	hard	maxlogins	3

# Override for Sysadmin(s)
@wheel	hard	nproc	unlimited
@wheel	hard	nofile	65535
@wheel	hard	maxlogins	unlimited
@wheel	hard	priority	-10
