# Disables auto-loading of TTY ldiscs (ldiscs - kernel modules to determine how data is interpreted) (some modules are old and many are obscure which definitely have some CVEs)
dev.tty.ldisc_autoload = 0
