# Stops SUID programs from creating core dumps on crash and stops core dumps from being stored anywhere respectively (core dumps may contain sensitive information)
fs.suid_dumpable = 0
kernel.core_pattern = /dev/null
