set block-policy drop
match in all scrub (no-df random-id)
block all
pass out proto { tcp, udp, icmp } all keep state
block drop inet proto icmp icmp-type { echoreq, timex, redir, maskreq, maskrep, routersol, routeradv, inforeq, inforep }
